version: '2.3'

services:

  web:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ../:/var/www
      - ../docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php
    networks:
      - "internal"

  php:
    build:
      context: ..
      dockerfile: docker/phpfpm/Dockerfile
    volumes:
      - ../:/var/www
      - ../docker/phpfpm/dev.ini:/usr/local/etc/php/conf.d/app.ini
      - ~/.composer:/.composer
    working_dir: /var/www
    user: '${UID}:${GID}'
    environment:
      PHP_IDE_CONFIG: "serverName=${IDE_SERVER_NAME}"
      XDEBUG_CONFIG: "remote_enable=1 remote_connect_back=1 idekey=PHPSTORM"
    restart: always
    depends_on:
      - database
    networks:
      - "internal"

  database:
    image: mariadb:latest
    volumes:
      - mysql-data:/var/lib/mysql
      - ../db/mysql-create-tables.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'oathservice'
    ports:
      - 3306:3306
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 20
    networks:
      - "internal"

networks:
  internal:

volumes:
  mysql-data: