monolog:
    handlers:
        prod-signaler:
            type: fingers_crossed
            action_level: ERROR
            passthru_level: NOTICE # this means that all message of level NOTICE or higher are always logged
            handler: main_syslog
            bubble: false # if we handle it, nothing else should
        main_syslog:
            type: syslog
            ident: stepup-keyserver
            facility: user
        console:
            type: console
            process_psr_3_messages: false
