surfnet_oath_secrets:
    type: rest
    resource: SURFnet\OATHBundle\Controller\SecretsController

surfnet_oath_oath:
    type: rest
    resource: SURFnet\OATHBundle\Controller\OathController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
