services:
  # When using PDO as storage
  SURFnet\OATHBundle\Services\UserStorage\PDO:
    arguments: ["%surfnet_oath.userstorage%"]
    calls:
     - [init]

  surfnet_oath.hash:
    class: SURFnet\OATHBundle\Services\Hash\Soft
