<?php

namespace SURFnet\OATHBundle\Controller;

use FOS\RestBundle\Controller\Annotations\Get;
use FOS\RestBundle\Controller\Annotations\View;
use Nelmio\ApiDocBundle\Annotation\ApiDoc;
use Symfony\Component\HttpFoundation\Request;

class OathController extends BaseController
{
    /**
     * @Get("/oath/challenge/ocra")
     * @View()
     * @ApiDoc(
     *  section="OATH",
     *  description="Get an OCRA challenge",
     *  statusCodes={
     *      200="Success, challenge is in the body",
     *      401="Invalid consumer key",
     *      500="General error, something went wrong",
     *  },
     * )
     */
    public function getOcraChallengeAction()
    {
        $responseCode = 200;
        try {
            $this->verifyConsumerKey();
            $data = $this->ocra->generateChallenge();
        } catch (\Exception $e) {
            $data = array('error' => $e->getMessage());
            $responseCode = 500;
            // only pass error code is it's a valid http status code
            if ($e->getCode() >= 200 && $e->getCode() <= 510) {
                $responseCode = $e->getCode() ?: 500;
            }
        }
        return $this->view($data, $responseCode);
    }

    /**
     * @Get("/oath/validate/ocra")
     * @View()
     * @ApiDoc(
     *  section="OATH",
     *  description="Validate a OCRA challenge against a response",
     *  parameters={
     *    {"name"="challenge", "dataType"="string", "required"=true, "description"="The original challenge generated by GET /oath/challenge/ocra"},
     *    {"name"="response", "dataType"="string", "required"=true, "description"="The response to validate the challenge against"},
     *    {"name"="userId", "dataType"="string", "required"=true, "description"="The user id"},
     *    {"name"="sessionKey", "dataType"="string", "required"=true, "description"="The session key"}
     *  },
     *  statusCodes={
     *      204="Success, challenge is valid",
     *      400="Challenge is not valid",
     *      401="Invalid consumer key",
     *      500="General error, something went wrong",
     *  },
     * )
     */
    public function validateOcraChallengeAction(Request $request)
    {
        $responseCode = 204;
        $data = null;
        try {
            $this->verifyConsumerKey();
            $secret = null;
            $userId = $request->get('userId');
            if ($userId !== null) {
                $secret = $this->userStorage->getSecret($userId);
            }
            $result = $this->ocra->validateResponse($request->get('response'), $request->get('challenge'), $secret, $request->get('sessionKey'));
            if (!$result) {
                $responseCode = 400;
            }
        } catch (\Exception $e) {
            $data = array('error' => $e->getMessage());
            $responseCode = 500;
            // only pass error code is it's a valid http status code
            if ($e->getCode() >= 200 && $e->getCode() <= 510) {
                $responseCode = $e->getCode() ?: 500;
            }
        }
        return $this->view($data, $responseCode);
    }

    /**
     * @Get("/oath/validate/hotp")
     * @View()
     * @ApiDoc(
     *  section="OATH",
     *  description="Validate a HOTP challenge against a response",
     *  parameters={
     *    {"name"="response", "dataType"="string", "required"=true, "description"="The response to validate"},
     *    {"name"="userId", "dataType"="string", "required"=true, "description"="The user id"},
     *  },
     *  statusCodes={
     *      204="Success, challenge is valid",
     *      400="Challenge is not valid",
     *      401="Invalid consumer key",
     *      500="General error, something went wrong",
     *  },
     * )
     */
    public function validateHotpChallengeAction(Request $request)
    {
        $responseCode = 204;
        $data = null;
        try {
            $this->verifyConsumerKey();
            $result = $this->hotp->validateResponse((string) $request->get('response'), (string) $request->get('userId'), $this->userStorage);
            if (!$result) {
                $responseCode = 400;
            }
        } catch (\Exception $e) {
            $data = array('error' => $e->getMessage());
            $responseCode = 500;
            // only pass error code is it's a valid http status code
            if ($e->getCode() >= 200 && $e->getCode() <= 510) {
                $responseCode = $e->getCode() ?: 500;
            }
        }
        return $this->view($data, $responseCode);
    }

    /**
     * @Get("/oath/validate/totp")
     * @View()
     * @ApiDoc(
     *  section="OATH",
     *  description="Validate a TOTP challenge against a response",
     *  parameters={
     *    {"name"="response", "dataType"="string", "required"=true, "description"="The response to validate the challenge against"},
     *    {"name"="userId", "dataType"="string", "required"=true, "description"="The user id"},
     *  },
     *  statusCodes={
     *      204="Success, challenge is valid",
     *      400="Challenge is not valid",
     *      401="Invalid consumer key",
     *      500="General error, something went wrong",
     *  },
     * )
     */
    public function validateTotpChallengeAction(Request $request)
    {
        $responseCode = 204;
        $data = null;
        try {
            $this->verifyConsumerKey();
            $result = $this->totp->validateResponse($request->get('response'), $request->get('userId'), $this->userStorage);
            if (!$result) {
                $responseCode = 400;
            }
        } catch (\Exception $e) {
            $data = array('error' => $e->getMessage());
            $responseCode = 500;
            // only pass error code is it's a valid http status code
            if ($e->getCode() >= 200 && $e->getCode() <= 510) {
                $responseCode = $e->getCode() ?: 500;
            }
        }
        return $this->view($data, $responseCode);
    }
}
